import type { Metadata } from 'next';
import Link from 'next/link';
import { tmdbDiscover, tmdbImage, slugify, type TmdbTitle } from '@/lib/tmdb';
import SiteHeader from '@/components/SiteHeader';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Discover What to Watch', description: 'Tell Cinevero your mood, time and taste. Get movie and series recommendations with a clear reason for each match.', alternates: { canonical: '/discover' } };
type SearchParams = { mood?: string; time?: string; genre?: string; sort?: string };
const moods: Record<string,{label:string;genres:string;reason:string}> = {
  feelgood:{label:'Feel-good',genres:'35,10749',reason:'light, warm and easy to enjoy'}, adrenaline:{label:'Adrenaline',genres:'28,53',reason:'fast, tense and high-energy'}, dark:{label:'Dark',genres:'27,53,9648',reason:'dark, suspenseful and atmospheric'}, mindbending:{label:'Mind-bending',genres:'878,9648',reason:'thought-provoking and mysterious'}, emotional:{label:'Emotional',genres:'18,10749',reason:'character-driven and emotional'}
};
const genres=[['28','Action'],['35','Comedy'],['18','Drama'],['27','Horror'],['878','Sci-Fi'],['53','Thriller'],['9648','Mystery'],['10749','Romance']];
const times=[['60','Under 1 hour'],['90','Under 90 min'],['120','Under 2 hours'],['150','Under 2h 30m'],['240','Any length']];
function titleOf(x:TmdbTitle){return x.title||x.name||x.original_title||x.original_name||'Untitled'}
function yearOf(x:TmdbTitle){return (x.release_date||x.first_air_date||'').slice(0,4)}
function ratingOf(x:TmdbTitle){return typeof x.vote_average==='number'&&x.vote_average>0?x.vote_average.toFixed(1):'N/A'}
function typeOf(x:TmdbTitle){return x.media_type==='tv'||x.name?'series':'movie'}
function Card({item,reason}:{item:TmdbTitle;reason:string}){const title=titleOf(item),type=typeOf(item),rating=ratingOf(item);return <Link href={`/${type}/${slugify(title)}-${item.id}`} className="group block rounded-2xl focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600"><article className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm transition group-hover:-translate-y-1 group-hover:shadow-lg"><div className="aspect-[2/3] bg-zinc-100">{item.poster_path?<img src={tmdbImage(item.poster_path,'w342')} alt={`${title} poster`} loading="lazy" decoding="async" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-xs text-zinc-400">No poster</div>}</div><div className="p-4"><div className="flex items-center gap-2 text-[11px] font-semibold text-zinc-500"><span className="rounded-full bg-zinc-100 px-2 py-1">{type==='movie'?'Movie':'Series'}</span>{yearOf(item)&&<span>{yearOf(item)}</span>}{rating!=='N/A'&&<span>★ {rating}</span>}</div><h2 className="mt-3 line-clamp-2 min-h-12 text-base font-bold leading-6">{title}</h2><p className="mt-2 text-xs leading-5 text-zinc-500">Why it matches: {reason}.</p></div></article></Link>}
export default async function DiscoverPage({searchParams}:{searchParams:Promise<SearchParams>}){
  const p=await searchParams; const mood=moods[p.mood||'']||null; const time=Number(p.time||'120'); const genre=p.genre||''; const genreFilter=mood?.genres&&!genre?mood.genres:genre||undefined; const runtimeMax=Number.isFinite(time)&&time<240?time:undefined; const sortBy=p.sort==='rating'?'vote_average.desc':p.sort==='newest'?'primary_release_date.desc':'popularity.desc'; const minRating=p.sort==='rating'?6:0;
  const [movies,series]=await Promise.all([tmdbDiscover('movie',1,{genreId:genreFilter,runtimeMax,voteAverageMin:minRating,sortBy}).catch(()=>({results:[],total_pages:0})),tmdbDiscover('tv',1,{genreId:genreFilter,voteAverageMin:minRating,sortBy}).catch(()=>({results:[],total_pages:0}))]);
  const combined=[...movies.results.map(x=>({...x,media_type:'movie' as const})),...series.results.map(x=>({...x,media_type:'tv' as const}))].sort((a,b)=>(b.popularity||0)-(a.popularity||0)); const reason=mood?.reason||(genre?`${genres.find(([id])=>id===genre)?.[1]||'genre'} pick`:'a popular match for your taste');
  return <div className="min-h-screen bg-zinc-50 text-zinc-950"><SiteHeader/><main className="mx-auto max-w-[1180px] px-4 py-8 sm:px-6 sm:py-12"><section className="rounded-3xl bg-zinc-950 px-6 py-9 text-white sm:px-10 sm:py-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-red-400">CINEVERO DISCOVER</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">What do you feel like watching?</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-300 sm:text-base">Choose a few signals. Cinevero turns them into a short list instead of making you scroll through hundreds of titles.</p></section>
  <form method="get" className="mt-6 rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-7"><div className="grid gap-6 lg:grid-cols-4"><fieldset><legend className="text-sm font-bold">Mood</legend><div className="mt-3 flex flex-wrap gap-2">{Object.entries(moods).map(([id,m])=><button key={id} name="mood" value={id} className={`rounded-full border px-3 py-2 text-xs font-semibold ${p.mood===id?'border-red-600 bg-red-600 text-white':'border-zinc-200 hover:border-red-400'}`}>{m.label}</button>)}</div></fieldset><fieldset><legend className="text-sm font-bold">Time available</legend><div className="mt-3 flex flex-wrap gap-2">{times.map(([id,label])=><button key={id} name="time" value={id} className={`rounded-full border px-3 py-2 text-xs font-semibold ${p.time===id?'border-red-600 bg-red-600 text-white':'border-zinc-200 hover:border-red-400'}`}>{label}</button>)}</div></fieldset><fieldset><legend className="text-sm font-bold">Genre</legend><div className="mt-3 flex flex-wrap gap-2">{genres.map(([id,label])=><button key={id} name="genre" value={id} className={`rounded-full border px-3 py-2 text-xs font-semibold ${p.genre===id?'border-red-600 bg-red-600 text-white':'border-zinc-200 hover:border-red-400'}`}>{label}</button>)}</div></fieldset><fieldset><legend className="text-sm font-bold">Sort</legend><div className="mt-3 flex flex-wrap gap-2">{[['popular','Popular'],['rating','Top rated'],['newest','Newest']].map(([id,label])=><button key={id} name="sort" value={id} className={`rounded-full border px-3 py-2 text-xs font-semibold ${p.sort===id?'border-red-600 bg-red-600 text-white':'border-zinc-200 hover:border-red-400'}`}>{label}</button>)}</div></fieldset></div><div className="mt-6 flex flex-wrap gap-3"><button type="submit" className="rounded-xl bg-zinc-950 px-5 py-3 text-sm font-bold text-white hover:bg-zinc-800">Show my matches</button><Link href="/discover" className="rounded-xl border border-zinc-200 px-5 py-3 text-sm font-bold">Reset</Link></div></form>
  <section className="mt-10"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-red-600">Your shortlist</p><h2 className="mt-1 text-2xl font-black sm:text-3xl">{combined.length?`${Math.min(combined.length,5)} matches worth checking`:'No matches yet'}</h2></div>{mood&&<p className="max-w-md text-sm text-zinc-500">Selected mood: <strong>{mood.label}</strong>. Showing titles that fit a {reason} profile.</p>}</div>{combined.length?<div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{combined.slice(0,5).map(item=><Card key={`${item.media_type}-${item.id}`} item={item} reason={reason}/>)}</div>:<div className="rounded-2xl border border-dashed border-zinc-300 bg-white p-10 text-center text-sm text-zinc-500">Try removing one filter or choosing another mood.</div>}</section>
  <section className="mt-12 border-t border-zinc-200 pt-8"><h2 className="text-lg font-bold">Keep exploring</h2><div className="mt-4 flex flex-wrap gap-2"><Link href="/movie" className="rounded-full border border-zinc-200 bg-white px-4 py-2 text-sm font-semibold">Browse movies</Link><Link href="/series" className="rounded-full border border-zinc-200 bg-white px-4 py-2 text-sm font-semibold">Browse series</Link><Link href="/genres" className="rounded-full border border-zinc-200 bg-white px-4 py-2 text-sm font-semibold">Explore genres</Link></div></section><p className="mt-10 text-xs text-zinc-400">Recommendations use movie and series metadata supplied by TMDB. Cinevero does not host movie or TV files.</p></main></div>;
}
