import { NextRequest, NextResponse } from 'next/server';

const cache = new Map<string, { expires: number; body: unknown }>();
const baseUrl = () => process.env.MOVIE_API_BASE_URL?.replace(/\/$/, '');
function listFrom(data: any) { if (Array.isArray(data)) return data; return data?.videos || data?.results || data?.data?.videos || data?.data || data?.items || []; }
function normalize(item: any) { const id = item?.id ?? item?.movie_id ?? item?.video_id ?? item?.slug; const image = item?.thumbnail || item?.poster || item?.poster_path || item?.image || item?.cover || item?.default_thumb?.src || item?.thumb; return { ...item, id: id == null ? '' : String(id), title: item?.title || item?.name || item?.original_title || 'Untitled title', thumbnail: image, default_thumb: { src: image }, thumbs: image ? [{ src: image }] : [], year: item?.year || item?.release_year || item?.release_date?.slice?.(0, 4), rate: item?.rate ?? item?.rating ?? item?.vote_average, views: item?.views ?? item?.view_count, quality: item?.quality || item?.resolution }; }
function makeUrl(path: string, params: URLSearchParams) { const base = baseUrl(); if (!base) return null; const template = path || process.env.MOVIE_API_SEARCH_PATH || '/movies'; const url = new URL(template.startsWith('http') ? template : `${base}${template.startsWith('/') ? '' : '/'}${template}`); const mapping: Record<string, string> = { query: process.env.MOVIE_API_QUERY_PARAM || 'query', page: process.env.MOVIE_API_PAGE_PARAM || 'page', per_page: process.env.MOVIE_API_LIMIT_PARAM || 'per_page', order: process.env.MOVIE_API_ORDER_PARAM || 'order' }; for (const [key, value] of params) if (['query', 'page', 'per_page', 'order'].includes(key)) url.searchParams.set(mapping[key], value); if (process.env.MOVIE_API_KEY) url.searchParams.set(process.env.MOVIE_API_KEY_PARAM || 'api_key', process.env.MOVIE_API_KEY); return url; }
async function fetchWithTimeout(url: URL) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 10000); try { return await fetch(url, { signal: controller.signal, cache: 'no-store', headers: { Accept: 'application/json', ...(process.env.MOVIE_API_KEY && process.env.MOVIE_API_KEY_HEADER ? { [process.env.MOVIE_API_KEY_HEADER]: process.env.MOVIE_API_KEY } : {}) } }); } finally { clearTimeout(timer); } }
export async function GET(request: NextRequest) { const params = request.nextUrl.searchParams; const base = baseUrl(); if (!base) return NextResponse.json({ error: 'Movie API is not configured. Set MOVIE_API_BASE_URL and MOVIE_API_SEARCH_PATH.', videos: [], total_pages: 0 }, { status: 503 }); const url = makeUrl(process.env.MOVIE_API_SEARCH_PATH || '/movies', params); if (!url) return NextResponse.json({ error: 'Invalid movie API configuration.' }, { status: 500 }); const key = url.toString().replace(process.env.MOVIE_API_KEY || '', 'REDACTED'); const cached = cache.get(key); if (cached && cached.expires > Date.now()) return NextResponse.json(cached.body, { headers: { 'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=300' } }); try { const response = await fetchWithTimeout(url); const text = await response.text(); const data = text ? JSON.parse(text) : null; if (!response.ok) return NextResponse.json({ error: data?.error || `Movie API returned HTTP ${response.status}`, videos: [] }, { status: 502 }); const videos = listFrom(data).map(normalize).filter((item: any) => item.id); const total = Number(data?.total_count ?? data?.total ?? data?.pagination?.total ?? videos.length); const perPage = Number(params.get('per_page') || 24); const body = { videos, total_count: total, total_pages: Number(data?.total_pages || data?.pagination?.total_pages || Math.max(1, Math.ceil(total / perPage))), page: Number(params.get('page') || 1), per_page: perPage, provider: 'private-movie-api' }; cache.set(key, { expires: Date.now() + 60000, body }); return NextResponse.json(body, { headers: { 'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=300' } }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to reach movie API', videos: [], total_pages: 0 }, { status: 502 }); } }
