import type { Metadata } from 'next';
import Link from 'next/link';
import { Star } from 'lucide-react';
import SiteHeader from '@/components/SiteHeader';
import { slugify, tmdbImage, tmdbSearch } from '@/lib/tmdb';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://watchmovies4.vercel.app';
export const metadata: Metadata = { title: 'Search Movies & TV Series', description: 'Search movies and TV series on Cinevero.', alternates: { canonical: `${SITE_URL}/search` } };

export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string; type?: string; year?: string; sort?: string }> }) {
  const { q, page: pageParam, type = 'all', year = '', sort = 'relevance' } = await searchParams;
  const query = q?.trim() || '';
  const requested = Number(pageParam); const page = Number.isFinite(requested) && requested > 0 ? Math.min(Math.floor(requested), 500) : 1;
  const data = query ? await tmdbSearch(query, page).catch(() => ({ results: [], total_pages: 0, total_results: 0 })) : { results: [], total_pages: 0, total_results: 0 };
  let results = data.results.filter((x: any) => x.media_type === 'movie' || x.media_type === 'tv');
  if (type === 'movie' || type === 'tv') results = results.filter((x: any) => x.media_type === type);
  if (/^\d{4}$/.test(year)) results = results.filter((x: any) => (x.release_date || x.first_air_date || '').startsWith(year));
  if (sort === 'rating') results.sort((a: any, b: any) => (b.vote_average || 0) - (a.vote_average || 0));
  if (sort === 'popularity') results.sort((a: any, b: any) => (b.popularity || 0) - (a.popularity || 0));
  if (sort === 'newest') results.sort((a: any, b: any) => (b.release_date || b.first_air_date || '').localeCompare(a.release_date || a.first_air_date || ''));
  if (sort === 'title') results.sort((a: any, b: any) => (a.title || a.name || '').localeCompare(b.title || b.name || ''));
  const totalPages = Math.min(data.total_pages || 0, 500);
  const pageUrl = (p: number) => `/search?q=${encodeURIComponent(query)}&page=${p}&type=${encodeURIComponent(type)}&year=${encodeURIComponent(year)}&sort=${encodeURIComponent(sort)}`;
  return <main className="min-h-screen bg-white text-zinc-900"><SiteHeader /><div className="mx-auto max-w-[1180px] px-4 py-8 sm:px-6 sm:py-10">
    <form role="search" action="/search" className="flex overflow-hidden rounded-xl border border-zinc-300 bg-white focus-within:border-red-500 focus-within:ring-2 focus-within:ring-red-500/10"><label className="sr-only" htmlFor="search-query">Search movies and series</label><input id="search-query" name="q" defaultValue={query} placeholder="Search movies and series" className="min-w-0 flex-1 px-4 py-3 text-sm outline-none"/><button type="submit" aria-label="Search" className="bg-red-600 px-5 text-white hover:bg-red-700">Search</button></form>
    <div className="mt-8 flex flex-col gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-red-600">Cinevero search</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">{query ? <>Results for “{query}”</> : 'Search movies and series'}</h1>{query && <p className="mt-2 text-sm text-zinc-500">{data.total_results.toLocaleString()} results · Page {page} of {Math.max(totalPages, 1)}</p>}</div>
      {query && <form method="get" className="grid grid-cols-2 gap-2 rounded-xl border border-zinc-200 bg-zinc-50 p-3 sm:grid-cols-4 lg:flex lg:items-center"><input type="hidden" name="q" value={query}/><label className="sr-only" htmlFor="type">Type</label><select id="type" name="type" defaultValue={type} className="rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm"><option value="all">All types</option><option value="movie">Movies</option><option value="tv">Series</option></select><label className="sr-only" htmlFor="year">Year</label><input id="year" name="year" defaultValue={year} inputMode="numeric" pattern="[0-9]{4}" placeholder="Year" className="rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm"/><label className="sr-only" htmlFor="sort">Sort</label><select id="sort" name="sort" defaultValue={sort} className="rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm"><option value="relevance">Sort: Relevance</option><option value="popularity">Popularity</option><option value="rating">Rating</option><option value="newest">Newest</option><option value="title">A–Z</option></select><button className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white hover:bg-zinc-800">Apply filters</button></form>}
    </div>
    {!query ? <div className="mt-10 rounded-2xl border border-dashed border-zinc-300 px-6 py-14 text-center"><h2 className="text-lg font-semibold">Start with a title, actor or series</h2><p className="mt-2 text-sm text-zinc-500">Use the search field above to explore Cinevero.</p></div> : results.length === 0 ? <div className="mt-10 rounded-2xl border border-dashed border-zinc-300 px-6 py-14 text-center"><h2 className="text-lg font-semibold">No matching titles</h2><p className="mt-2 text-sm text-zinc-500">Try another title or loosen your filters.</p></div> : <div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-4 lg:grid-cols-6">{results.map((item: any) => { const tv = item.media_type === 'tv'; const title = item.title || item.name || 'Untitled'; const itemYear = (item.release_date || item.first_air_date || '').slice(0,4); const rating = typeof item.vote_average === 'number' && item.vote_average > 0 ? item.vote_average.toFixed(1) : 'N/A'; return <Link key={`${item.media_type}-${item.id}`} href={`/${tv ? 'series' : 'movie'}/${slugify(title)}-${item.id}`} className="group min-w-0 rounded-xl focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600"><article><div className="aspect-[2/3] overflow-hidden rounded-xl bg-zinc-100">{item.poster_path ? <img src={tmdbImage(item.poster_path,'w342')} alt={`${title} poster`} loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]"/> : <div className="flex h-full items-center justify-center text-xs text-zinc-400">No poster</div>}</div><div className="mt-2"><div className="flex items-center gap-2 text-[11px] font-semibold"><span className="rounded-full bg-zinc-100 px-2 py-1 text-zinc-600">{tv ? 'Series' : 'Movie'}</span><span className="text-zinc-500">{itemYear || '—'}</span></div><h2 className="mt-2 line-clamp-2 min-h-10 text-sm font-semibold group-hover:text-red-600">{title}</h2><span className="mt-1 inline-flex items-center gap-1 text-xs text-zinc-500"><Star size={11} fill="currentColor" aria-hidden="true"/>{rating === 'N/A' ? 'Not rated' : `${rating}/10`}</span></div></article></Link>})}</div>}
    {query && totalPages > 1 && <nav className="mt-10 flex flex-wrap items-center justify-center gap-2" aria-label="Search pagination"><Link href={page > 1 ? pageUrl(page - 1) : pageUrl(1)} aria-disabled={page <= 1} className={`rounded-lg border px-4 py-2 text-sm font-medium ${page <= 1 ? 'pointer-events-none opacity-40' : 'hover:border-red-500 hover:text-red-600'}`}>Previous</Link><span className="px-3 text-sm text-zinc-500">Page {page} of {totalPages}</span><Link href={page < totalPages ? pageUrl(page + 1) : pageUrl(totalPages)} aria-disabled={page >= totalPages} className={`rounded-lg border px-4 py-2 text-sm font-medium ${page >= totalPages ? 'pointer-events-none opacity-40' : 'hover:border-red-500 hover:text-red-600'}`}>Next</Link></nav>}
  </div></main>;
}
