'use client';
import type { FormEvent } from 'react';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { BarChart3, ArrowLeft, KeyRound, LogIn, LogOut, RefreshCw, Save, Search, Server, ShieldCheck, Globe2, Monitor, Smartphone, Chrome } from 'lucide-react';

type Settings = { query:string; order:string; per_page:number|''; thumbsize:string; gay:number|''; lq:number|''; format:string; method:string; video_id:string; api_base_url:string; api_search_path:string; api_details_path:string; api_timeout_ms:number|''; api_format:string; items_per_page:number|''; cache_duration:number|''; google_site_verification:string; bing_site_verification:string; yandex_site_verification:string; naver_site_verification:string; baidu_site_verification:string; indexnow_key:string };
const EMPTY:Settings={query:'all',order:'latest',per_page:24,thumbsize:'medium',gay:0,lq:1,format:'json',method:'search',video_id:'',api_base_url:'https://www.eporner.com/api/v2',api_search_path:'/video/search',api_details_path:'/video/id',api_timeout_ms:10000,api_format:'json',items_per_page:24,cache_duration:0,google_site_verification:'',bing_site_verification:'',yandex_site_verification:'',naver_site_verification:'',baidu_site_verification:'',indexnow_key:''};
const input='w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white outline-none focus:border-red-500/60';
const orders=['latest','longest','shortest','top-rated','most-popular','top-weekly','top-monthly']; const pages=[12,24,48,96]; const thumbs=['small','medium','big']; const formats=['json','xml'];

type Stat={name:string;count:number}; type Analytics={pageViews:number;uniqueVisitors:number;countries:Stat[];devices:Stat[];browsers:Stat[];operatingSystems:Stat[];pages:Stat[];referrers:Stat[];dailyVisitors:{date:string;views:number}[];periodDays:number};

export default function AdminPage(){
 const [auth,setAuth]=useState<boolean|null>(null),[user,setUser]=useState(''),[pass,setPass]=useState(''),[settings,setSettings]=useState(EMPTY),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState(''),[analytics,setAnalytics]=useState<Analytics|null>(null),[days,setDays]=useState(30),[analyticsLoading,setAnalyticsLoading]=useState(false);
 useEffect(()=>{fetch('/api/admin/login',{cache:'no-store'}).then(r=>r.json()).then(d=>setAuth(Boolean(d.authenticated))).catch(()=>setAuth(false))},[]);
 useEffect(()=>{if(auth){loadSettings();loadAnalytics(days)}},[auth]);
 async function loadSettings(){try{const r=await fetch('/api/settings',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setSettings({...EMPTY,...d.settings})}catch(e){setError(e instanceof Error?e.message:'Failed to load settings')}}
 async function loadAnalytics(period=days){setAnalyticsLoading(true);try{const r=await fetch(`/api/admin/analytics?days=${period}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setAnalytics(d)}catch(e){setError(e instanceof Error?e.message:'Failed to load analytics')}finally{setAnalyticsLoading(false)}}
 const update=(k:keyof Settings,v:string|number)=>{setSettings(s=>({...s,[k]:v}));setMsg('');setError('')};
 async function login(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:user,password:pass})});const d=await r.json();if(!r.ok)throw Error(d.error||'Invalid credentials');setAuth(true)}catch(e){setError(e instanceof Error?e.message:'Login failed')}finally{setBusy(false)}}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});const d=await r.json();if(!r.ok)throw Error(d.error);setSettings({...EMPTY,...d.settings});setMsg('Settings saved successfully')}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/admin/login',{method:'DELETE'});setAuth(false)}
 if(auth===null)return <div className="min-h-screen bg-[#0a0a0a]"/>;
 if(!auth)return <div className="min-h-screen bg-[#0a0a0a] text-zinc-200"><Header loggedIn={false}/><main className="flex min-h-[calc(100vh-4rem)] items-center justify-center"><form onSubmit={login} className="w-full max-w-sm rounded-2xl border border-white/10 bg-[#141414] p-6"><div className="text-center"><KeyRound className="mx-auto mb-4 text-red-400"/><h1 className="text-2xl font-bold text-white">Admin Dashboard</h1><p className="mt-2 text-sm text-zinc-500">Sign in to manage the portal.</p></div><input className={`${input} mt-6`} value={user} onChange={e=>setUser(e.target.value)} placeholder="Username" autoComplete="username"/><input className={`${input} mt-3`} type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Password" autoComplete="current-password"/><button disabled={busy} className="mt-4 w-full rounded-xl bg-red-600 px-4 py-3 font-bold text-white disabled:opacity-50"><LogIn className="mr-2 inline h-4 w-4"/>{busy?'Signing in…':'Sign in'}</button>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}</form></main></div>;
 return <div className="min-h-screen bg-[#0a0a0a] text-zinc-200"><Header loggedIn onLogout={logout}/><main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6">
  <div><p className="text-xs font-bold uppercase tracking-[.2em] text-red-400">Elovex Administration</p><h1 className="mt-2 text-3xl font-black text-white">Admin Dashboard</h1><p className="mt-2 text-sm text-zinc-500">Analytics, SEO verification, provider configuration and portal settings.</p></div>
  <section className="rounded-2xl border border-white/10 bg-[#141414] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold text-white"><BarChart3 className="text-red-400"/> Visitor Analytics</h2><p className="text-sm text-zinc-500">Country, city, device, browser, OS, pages, referrers and unique visitors.</p></div><div className="flex gap-2"><select className={input} value={days} onChange={e=>{const d=Number(e.target.value);setDays(d);loadAnalytics(d)}}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><button onClick={()=>loadAnalytics()} className="rounded-xl border border-white/10 px-3 text-zinc-300"><RefreshCw className={analyticsLoading?'animate-spin':''} size={16}/></button></div></div>
   {analytics&&<><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric title="Page views" value={analytics.pageViews}/><Metric title="Unique visitors" value={analytics.uniqueVisitors}/><Metric title="Top country" value={analytics.countries[0]?.name||'—'}/><Metric title="Top device" value={analytics.devices[0]?.name||'—'}/></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><Stats title="Countries" icon={<Globe2 size={16}/>} data={analytics.countries}/><Stats title="Devices" icon={<Smartphone size={16}/>} data={analytics.devices}/><Stats title="Browsers" icon={<Chrome size={16}/>} data={analytics.browsers}/><Stats title="Operating systems" icon={<Monitor size={16}/>} data={analytics.operatingSystems}/><Stats title="Top pages" data={analytics.pages}/><Stats title="Traffic sources" data={analytics.referrers.filter(x=>x.name!=='Unknown')}/></div><div className="mt-4 rounded-xl border border-white/10 p-4"><h3 className="mb-3 font-semibold text-white">Daily traffic</h3><div className="flex h-28 items-end gap-1 overflow-x-auto">{analytics.dailyVisitors.map(d=><div key={d.date} title={`${d.date}: ${d.views}`} className="min-w-2 flex-1 rounded-t bg-red-500/70" style={{height:`${Math.max(5,(d.views/Math.max(...analytics.dailyVisitors.map(x=>x.views),1))*100)}%`}}/>)}</div></div></>}
   {!analytics&&<p className="mt-5 rounded-xl bg-black/20 p-5 text-sm text-zinc-500">{analyticsLoading?'Loading analytics…':'Analytics will appear after the database table is available.'}</p>}
  </section>
  <form onSubmit={save} className="space-y-6">
   <Section title="Search & API Settings" icon={<Server/>}><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field l="Search Query"><input className={input} value={settings.query} onChange={e=>update('query',e.target.value)}/></Field><Field l="Order"><Select value={settings.order} options={orders} onChange={v=>update('order',v)}/></Field><Field l="Per Page"><Select value={settings.per_page} options={pages} onChange={v=>update('per_page',Number(v))}/></Field><Field l="Thumb Size"><Select value={settings.thumbsize} options={thumbs} onChange={v=>update('thumbsize',v)}/></Field><Field l="Filter A"><Select value={settings.gay} options={[0,1,2]} onChange={v=>update('gay',Number(v))}/></Field><Field l="Filter B"><Select value={settings.lq} options={[0,1,2]} onChange={v=>update('lq',Number(v))}/></Field><Field l="API Base URL" full><input className={input} value={settings.api_base_url} onChange={e=>update('api_base_url',e.target.value)}/></Field><Field l="Search Path"><input className={input} value={settings.api_search_path} onChange={e=>update('api_search_path',e.target.value)}/></Field><Field l="Details Path"><input className={input} value={settings.api_details_path} onChange={e=>update('api_details_path',e.target.value)}/></Field><Field l="Timeout ms"><input className={input} type="number" value={settings.api_timeout_ms} onChange={e=>update('api_timeout_ms',Number(e.target.value))}/></Field><Field l="Items Per Page"><Select value={settings.items_per_page} options={pages} onChange={v=>update('items_per_page',Number(v))}/></Field><Field l="Cache Seconds"><Select value={settings.cache_duration} options={[0,60,300,3600]} onChange={v=>update('cache_duration',Number(v))}/></Field></div></Section>
   <Section title="Search Engine Verification" icon={<ShieldCheck/>}><p className="mb-5 text-sm text-zinc-500">Paste the verification values from each webmaster console. They are stored in Supabase and automatically emitted as the correct meta tags.</p><div className="grid gap-4 md:grid-cols-2"><Verify l="Google Search Console" v={settings.google_site_verification} onChange={v=>update('google_site_verification',v)} ph="google-site-verification content"/><Verify l="Bing Webmaster Tools" v={settings.bing_site_verification} onChange={v=>update('bing_site_verification',v)} ph="msvalidate.01 content"/><Verify l="Yandex Webmaster" v={settings.yandex_site_verification} onChange={v=>update('yandex_site_verification',v)} ph="yandex-verification content"/><Verify l="Naver Search Advisor" v={settings.naver_site_verification} onChange={v=>update('naver_site_verification',v)} ph="naver-site-verification content"/><Verify l="Baidu Webmaster" v={settings.baidu_site_verification} onChange={v=>update('baidu_site_verification',v)} ph="baidu-site-verification content"/><Verify l="IndexNow Key" v={settings.indexnow_key} onChange={v=>update('indexnow_key',v)} ph="IndexNow API key"/></div><div className="mt-5 rounded-xl border border-white/10 bg-black/20 p-4 text-xs leading-5 text-zinc-500">Supported verification slots: <b className="text-zinc-300">Google, Bing, Yandex, Naver, Baidu</b>. IndexNow is stored separately for future URL submission/instant indexing.</div></Section>
   <div className="flex justify-end gap-3 border-t border-white/10 pt-5"><button type="button" onClick={loadSettings} className="rounded-xl border border-white/10 px-4 py-3 text-sm">Reload</button><button disabled={busy} className="rounded-xl bg-red-600 px-5 py-3 text-sm font-bold text-white"><Save className="mr-2 inline h-4 w-4"/>{busy?'Saving…':'Save All Settings'}</button></div>{msg&&<p className="text-sm text-emerald-300">{msg}</p>}{error&&<p className="text-sm text-red-300">{error}</p>}
  </form>
 </main></div>;
}
function Header({loggedIn,onLogout}:{loggedIn:boolean;onLogout?:()=>void}){return <header className="sticky top-0 z-50 border-b border-white/10 bg-[#0a0a0a]/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><div className="font-black tracking-[.18em] text-white">ADMIN</div>{loggedIn&&<div className="flex gap-2"><Link href="/" className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs text-zinc-400"><ArrowLeft size={14}/>Portal</Link><button onClick={onLogout} className="flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-zinc-400"><LogOut size={14}/>Logout</button></div>}</div></header>}
function Section({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-[#141414] p-5 sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-white">{icon}<span>{title}</span></h2><div className="mt-5">{children}</div></section>}
function Field({l,children,full=false}:{l:string;children:React.ReactNode;full?:boolean}){return <label className={`block ${full?'md:col-span-2 lg:col-span-3':''}`}><span className="mb-2 block text-xs font-semibold text-zinc-300">{l}</span>{children}</label>}
function Select({value,options,onChange}:{value:string|number;options:(string|number)[];onChange:(v:string)=>void}){return <select className={input} value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={String(x)} value={x}>{x}</option>)}</select>}
function Verify({l,v,onChange,ph}:{l:string;v:string;onChange:(v:string)=>void;ph:string}){return <label><span className="mb-2 block text-xs font-semibold text-zinc-300">{l}</span><input className={input} value={v} onChange={e=>onChange(e.target.value)} placeholder={ph}/></label>}
function Metric({title,value}:{title:string;value:string|number}){return <div className="rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-zinc-500">{title}</p><p className="mt-1 truncate text-2xl font-black text-white">{typeof value==='number'?value.toLocaleString():value}</p></div>}
function Stats({title,data,icon}:{title:string;data:Stat[];icon?:React.ReactNode}){const max=Math.max(...data.map(x=>x.count),1);return <div className="rounded-xl border border-white/10 p-4"><h3 className="mb-3 flex items-center gap-2 font-semibold text-white">{icon}{title}</h3><div className="space-y-2">{data.slice(0,8).map(x=><div key={x.name} className="flex items-center gap-3 text-xs"><span className="w-28 truncate text-zinc-400">{x.name}</span><div className="h-2 flex-1 rounded bg-white/5"><div className="h-2 rounded bg-red-500/70" style={{width:`${Math.max(2,x.count/max*100)}%`}}/></div><span className="w-10 text-right text-zinc-500">{x.count}</span></div>)}</div></div>}
