import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Elovex privacy policy: what data we collect, why we use it, and your choices.',
  alternates: { canonical: '/privacy-policy' },
};

export default function PrivacyPolicyPage() {
  return <main className="mx-auto max-w-3xl px-5 py-12 text-zinc-800"><h1 className="text-3xl font-bold">Privacy Policy</h1><p className="mt-3 text-sm text-zinc-500">Last updated: September 11, 2026</p><section className="prose prose-zinc mt-8 max-w-none"><h2>Information we process</h2><p>Elovex is a video discovery website. We may process technical information such as browser type, device information, approximate location derived from IP, pages visited, and security events. We do not ask visitors to create an account to browse public pages.</p><h2>Local preferences</h2><p>We store the age-confirmation preference in your browser’s local storage. You can remove it through your browser settings. This preference is not a government-issued identity check.</p><h2>Analytics and service providers</h2><p>We may use analytics and infrastructure providers to understand performance, prevent abuse, and keep the site reliable. Providers may process limited technical data under their own policies.</p><h2>External content</h2><p>Video players, thumbnails, and links may be supplied by third-party providers. Their processing is governed by their own privacy policies. Review those policies before interacting with third-party content.</p><h2>Retention and security</h2><p>We retain information only as reasonably necessary for operations, security, legal compliance, and dispute handling. No internet service can guarantee absolute security.</p><h2>Your choices</h2><p>You may disable cookies or local storage in your browser, use content blockers, or contact us with a privacy request. Some site features may not work correctly after disabling storage.</p><h2>Contact</h2><p>For privacy questions or requests, use the <a href="/contact">Contact page</a>.</p><p className="text-sm text-zinc-500">This page is general information, not legal advice. Have counsel adapt it to your entity, jurisdiction, vendors, and actual data practices before relying on it as a legal notice.</p></section></main>;
}
