'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Menu, Search, X } from 'lucide-react';

type Props = { initialSearch?: string; initialPage?: number; initialOrder?: string; initialVideos?: unknown[]; initialTotalPages?: number; initialError?: string };

const EmptyRows = ({ count = 4 }: { count?: number }) => <div className="space-y-2.5">{Array.from({ length: count }).map((_, index) => <div key={index} className="h-3.5 animate-pulse rounded-sm bg-[#eeeeef]" style={{ width: `${68 + ((index * 13) % 28)}%` }} />)}</div>;

export default function VideoPortalClient({ initialSearch = '' }: Props) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [search, setSearch] = useState(initialSearch);
  const [searchOpen, setSearchOpen] = useState(false);
  const submitSearch = (event: React.FormEvent) => event.preventDefault();
  return <div className="min-h-screen bg-[#fff] text-[#27282b]">
    <header className="border-b border-[#e7e7e8] bg-white"><div className="mx-auto flex min-h-[68px] max-w-[1160px] items-center gap-6 px-4 sm:px-6"><button type="button" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)} className="rounded p-1.5 text-[#55565a] hover:bg-[#f2f2f3] md:hidden">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><Link href="/" className="shrink-0 text-[23px] font-black tracking-[-0.08em]"><span className="text-[#27282b]">ELO</span><span className="text-[#e52b43]">VEX</span></Link><form onSubmit={submitSearch} className="hidden min-w-0 flex-1 md:flex md:max-w-[430px]"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search" aria-label="Search" className="min-w-0 flex-1 border border-[#d9d9db] px-3 py-2 text-sm outline-none focus:border-[#e52b43]" /><button aria-label="Submit search" className="flex items-center gap-2 bg-[#e52b43] px-4 text-sm font-semibold text-white hover:bg-[#c92138]"><Search size={15} />Search</button></form><nav className="ml-auto hidden items-center gap-6 text-sm md:flex"><Link href="/" className="font-semibold text-[#27282b]">Home</Link><Link href="/" className="text-[#686a6f] hover:text-[#e52b43]">Movies</Link><Link href="/" className="text-[#686a6f] hover:text-[#e52b43]">Series</Link></nav><button type="button" aria-label="Open search" onClick={() => setSearchOpen(!searchOpen)} className="ml-auto rounded p-1.5 text-[#55565a] hover:bg-[#f2f2f3] md:hidden"><Search size={20} /></button></div>{menuOpen && <nav className="border-t border-[#e7e7e8] px-5 py-3 md:hidden"><div className="mx-auto flex max-w-[1160px] gap-5 text-sm font-medium"><Link href="/">Home</Link><Link href="/">Movies</Link><Link href="/">Series</Link></div></nav>}{searchOpen && <form onSubmit={submitSearch} className="border-t border-[#e7e7e8] p-3 md:hidden"><div className="mx-auto flex max-w-[1160px]"><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search movies or series" className="min-w-0 flex-1 border border-[#d9d9db] px-3 py-2 text-sm outline-none focus:border-[#e52b43]" /><button className="bg-[#e52b43] px-4 text-sm font-semibold text-white">Search</button></div></form>}</header>
    <main className="mx-auto max-w-[1160px] px-4 pb-16 sm:px-6"><section className="grid gap-5 py-6 md:grid-cols-2"><div className="border border-[#e4e4e6] bg-[#fafafa] p-5"><h2 className="mb-4 text-xs font-extrabold uppercase tracking-[0.12em] text-[#55565a]">New Episodes</h2><EmptyRows /><p className="mt-4 text-xs text-[#999a9e]">Your latest episodes will appear here.</p></div><div className="border border-[#e4e4e6] bg-[#fafafa] p-5"><h2 className="mb-4 text-xs font-extrabold uppercase tracking-[0.12em] text-[#55565a]">New Seasons</h2><EmptyRows count={4} /><p className="mt-4 text-xs text-[#999a9e]">New seasons will appear here.</p></div></section><section className="border-t border-[#dedee0] pt-7"><h1 className="text-[24px] font-bold tracking-[-0.03em] sm:text-[30px]">Elovex: Movies and Series Streaming</h1><p className="mt-2 text-sm text-[#77797e]">Browse movies and series in a simple, fast and responsive catalogue.</p></section><section className="mt-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-extrabold uppercase tracking-[0.1em] text-[#4d4f54]">Latest additions</h2><span className="text-xs text-[#a0a1a5]">Design preview</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">{Array.from({ length: 10 }).map((_, index) => <div key={index} className="border border-[#e5e5e7] bg-[#fafafa] p-2"><div className="aspect-[2/3] animate-pulse bg-[#ededee]" /><div className="mt-2 h-3 w-4/5 animate-pulse rounded-sm bg-[#e5e5e7]" /></div>)}</div><p className="py-8 text-center text-xs text-[#999a9e]">Movie information and thumbnails will be connected to your API later.</p></section><nav aria-label="Pagination" className="flex justify-center gap-1.5 border-t border-[#e7e7e8] pt-6"><span className="border border-[#e2e2e4] px-3 py-1.5 text-xs font-semibold text-[#e52b43]">1</span>{['2','3','4','5','…','246'].map((page) => <span key={page} className="border border-[#e2e2e4] px-3 py-1.5 text-xs text-[#77797e]">{page}</span>)}</nav></main>
    <footer className="border-t border-[#e7e7e8] bg-[#fafafa]"><div className="mx-auto flex max-w-[1160px] flex-col gap-2 px-4 py-6 text-xs text-[#8a8b90] sm:flex-row sm:items-center sm:justify-between sm:px-6"><span>© {new Date().getFullYear()} Elovex</span><div className="flex gap-4"><Link href="/contact" className="hover:text-[#e52b43]">Contact</Link><Link href="/privacy-policy" className="hover:text-[#e52b43]">Privacy</Link></div></div></footer>
  </div>;
}
