'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Menu, Search, X } from 'lucide-react';

type Props = { initialSearch?: string; initialPage?: number; initialOrder?: string; initialVideos?: unknown[]; initialTotalPages?: number; initialError?: string };
const genres = ['Action', 'Animation', 'Adventure', 'Comedy', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Romance', 'Science Fiction', 'Thriller'];
const years = ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016'];
const PlaceholderCard = ({ featured = false }: { featured?: boolean }) => <div className={`border border-[#e4e4e6] bg-white p-2 ${featured ? 'min-w-[150px] sm:min-w-0' : ''}`}><div className={`animate-pulse bg-[#ededee] ${featured ? 'aspect-[16/10]' : 'aspect-[2/3]'}`} /><div className="mt-2 h-3 w-4/5 animate-pulse rounded-sm bg-[#e7e7e8]" /><div className="mt-1 h-2.5 w-2/5 animate-pulse rounded-sm bg-[#eeeeef]" /></div>;
const EmptyRows = () => <div className="space-y-3">{[0, 1, 2, 3, 4].map((item) => <div key={item} className="h-3.5 animate-pulse rounded-sm bg-[#eeeeef]" style={{ width: `${65 + item * 6}%` }} />)}</div>;

export default function VideoPortalClient({ initialSearch = '' }: Props) {
  const [menuOpen, setMenuOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [search, setSearch] = useState(initialSearch);
  return <div className="elovex-shell min-h-screen bg-[#fff] text-[#292a2d]">
    <header className="border-b border-[#e5e5e7] bg-white"><div className="mx-auto flex min-h-[68px] max-w-[1180px] items-center gap-6 px-4 sm:px-6"><button aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)} className="rounded p-1.5 text-[#55565a] hover:bg-[#f2f2f3] md:hidden">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><Link href="/" className="shrink-0 text-[23px] font-black tracking-[-0.08em]"><span>ELO</span><span className="text-[#e52b43]">VEX</span></Link><form className="hidden min-w-0 flex-1 md:flex md:max-w-[440px]" onSubmit={(e) => e.preventDefault()}><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search" className="min-w-0 flex-1 border border-[#d8d8da] px-3 py-2 text-sm outline-none focus:border-[#e52b43]" /><button className="bg-[#e52b43] px-4 text-sm font-semibold text-white"><Search size={15} className="mr-2 inline" />Search</button></form><nav className="ml-auto hidden gap-6 text-sm md:flex"><Link href="/" className="font-semibold">Home</Link><Link href="/" className="text-[#6d6e73] hover:text-[#e52b43]">Movies</Link><Link href="/" className="text-[#6d6e73] hover:text-[#e52b43]">Series</Link></nav><button aria-label="Search" onClick={() => setSearchOpen(!searchOpen)} className="ml-auto rounded p-1.5 text-[#55565a] md:hidden"><Search size={20} /></button></div>{menuOpen && <nav className="border-t border-[#e5e5e7] px-5 py-3 md:hidden"><div className="flex gap-5 text-sm font-medium"><Link href="/">Home</Link><Link href="/">Movies</Link><Link href="/">Series</Link></div></nav>}{searchOpen && <form className="border-t border-[#e5e5e7] p-3 md:hidden" onSubmit={(e) => e.preventDefault()}><div className="flex"><input autoFocus value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search movies or series" className="min-w-0 flex-1 border border-[#d8d8da] px-3 py-2 text-sm outline-none" /><button className="bg-[#e52b43] px-4 text-sm font-semibold text-white">Search</button></div></form>}</header>
    <main className="mx-auto max-w-[1180px] px-4 pb-14 sm:px-6">
      <section className="overflow-x-auto py-6"><div className="flex gap-3 sm:grid sm:grid-cols-3 md:grid-cols-5 lg:grid-cols-6">{Array.from({ length: 6 }).map((_, i) => <PlaceholderCard key={i} featured />)}</div></section>
      <section className="grid gap-5 pb-7 md:grid-cols-2"><div className="border border-[#e4e4e6] bg-[#fafafa] p-5"><h2 className="mb-4 text-xs font-extrabold uppercase tracking-[0.1em] text-[#55565a]">New Episodes</h2><EmptyRows /><p className="mt-4 text-xs text-[#999a9e]">Your latest episodes will appear here.</p></div><div className="border border-[#e4e4e6] bg-[#fafafa] p-5"><h2 className="mb-4 text-xs font-extrabold uppercase tracking-[0.1em] text-[#55565a]">New Seasons</h2><EmptyRows /><p className="mt-4 text-xs text-[#999a9e]">Your latest seasons will appear here.</p></div></section>
      <section className="border-t border-[#dedee0] pt-7"><h1 className="text-[25px] font-bold tracking-[-0.03em] sm:text-[30px]">Elovex: Movies and Series Streaming</h1><p className="mt-2 text-sm text-[#77797e]">Browse movies and series in a simple, fast and responsive catalogue.</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">{Array.from({ length: 18 }).map((_, i) => <PlaceholderCard key={i} />)}</div><p className="py-8 text-center text-xs text-[#999a9e]">Movie information and thumbnails will be connected to your API later.</p></section>
      <nav aria-label="Pagination" className="flex flex-wrap justify-center gap-1.5 border-t border-[#e7e7e8] pt-6">{['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '…', '246'].map((page, i) => <span key={page} className={`border border-[#e2e2e4] px-3 py-1.5 text-xs ${i === 0 ? 'font-semibold text-[#e52b43]' : 'text-[#77797e]'}`}>{page}</span>)}</nav>
    </main>
    <footer className="border-t border-[#e5e5e7] bg-[#fafafa]"><div className="mx-auto grid max-w-[1180px] gap-8 px-4 py-8 text-xs text-[#77797e] sm:px-6 md:grid-cols-4"><div><h3 className="mb-3 font-bold uppercase tracking-wider text-[#45464a]">Main menu</h3><div className="space-y-2"><Link className="block hover:text-[#e52b43]" href="/">Home</Link><Link className="block hover:text-[#e52b43]" href="/">Movies</Link><Link className="block hover:text-[#e52b43]" href="/">Series</Link></div></div><div><h3 className="mb-3 font-bold uppercase tracking-wider text-[#45464a]">By Genre</h3><div className="grid grid-cols-2 gap-y-2">{genres.map((genre) => <span key={genre}>{genre}</span>)}</div></div><div><h3 className="mb-3 font-bold uppercase tracking-wider text-[#45464a]">By Year</h3><div className="grid grid-cols-2 gap-y-2">{years.map((year) => <span key={year}>{year}</span>)}</div></div><div><h3 className="mb-3 font-bold uppercase tracking-wider text-[#45464a]">By Version</h3><div className="space-y-2"><span className="block">English</span><span className="block">Original Version</span><span className="block">HD</span></div></div></div><div className="border-t border-[#e5e5e7] px-4 py-5 text-center text-xs text-[#999a9e]">© {new Date().getFullYear()} Elovex · Contact · Privacy</div></footer>
  </div>;
}
