create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text not null default '/',
  referrer text,
  country text,
  country_code text,
  region text,
  city text,
  device text,
  browser text,
  os text,
  user_agent text,
  visitor_hash text,
  is_bot boolean not null default false
);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_country_idx on public.analytics_events(country_code);
create index if not exists analytics_events_path_idx on public.analytics_events(path);
create index if not exists analytics_events_visitor_hash_idx on public.analytics_events(visitor_hash);
alter table public.analytics_events enable row level security;
insert into public.site_settings(key,value,value_type,description,updated_by,updated_at) values
('elovex_google_site_verification','','text','Google Search Console verification code','admin',now()),
('elovex_bing_site_verification','','text','Bing Webmaster Tools verification code','admin',now()),
('elovex_yandex_site_verification','','text','Yandex Webmaster verification code','admin',now()),
('elovex_naver_site_verification','','text','Naver Search Advisor verification code','admin',now()),
('elovex_baidu_site_verification','','text','Baidu Webmaster verification code','admin',now()),
('elovex_indexnow_key','','text','IndexNow API key','admin',now())
on conflict(key) do nothing;
